# Generated by Django 2.2.3 on 2019-09-07 16:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='接口名称')),
                ('project_id', models.IntegerField(null=True, verbose_name='项目ID')),
                ('tree', models.IntegerField(null=True, verbose_name='树节点id')),
                ('des', models.TextField(null=True, verbose_name='描述')),
                ('method', models.IntegerField(null=True, verbose_name='请求方式')),
                ('evn_id', models.IntegerField(null=True, verbose_name='环境id')),
                ('url', models.CharField(max_length=60, null=True, verbose_name='接口url')),
                ('para_list', models.TextField(null=True, verbose_name='参数列表')),
                ('creater', models.CharField(max_length=10, null=True, verbose_name='创建人')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateField(auto_now=True, verbose_name='最近修改时间')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 't_api',
                'ordering': ['id'],
            },
            managers=[
                ('apiQuery', django.db.models.manager.Manager()),
            ],
        ),
    ]
